### ISSUE TITLE
UdfEditor's GetFileByName doesn't appear to work for directories.

### ISSUE THREAD

**Issue by monyarm** [Finzenku/Ps2IsoTools#7]
Using GetAllFileFullNames I confirmed that the files I'm trying to replace exist.
The path I'm supplying is the same as what GetAllFileFullNames spits out. So the only reason it wouldn't work, would be that GetFileByName doesn't support directories.

**Comment by Finzenku** [comment]
I see what you mean. The UdfEditor is only checking against each files name regardless of what directory it is in. I should be able to push an update to have the UdfEditor defer to its internal UdfReader which has a better implementation of GetFileByName. I'll work on pushing an update today.
